### ISSUE TITLE
opening app via notification crashes

### ISSUE THREAD

**Issue by lefuglyduck** [mywalkb/LSPosed_mod#83]
### Steps to reproduce

1. Click the "LSPosed loaded" notification. Nothing happens (app doesn't launch)
2. Do it again. This time the app crashes. 

Using graphene OS

### Expected behaviour

Not crash. Open LSPosed manager.

### Actual behaviour

Crash (on second tap). On first tap nothing happens.

### Xposed Module List

```shell
Firefox no home button
Google maps tweaks
```

### Magisk Module List

```shell
ICS sounds
Live boot 
Pixel tensor audio decompressor
Volte and wifi call enabler 
LSPosed
Zygisk-sui
Zygisk-detach
```

### LSPosed version

7244

### Android version

14

### Magisk version

26.4 (26400) kitsune mask

### Riru version

n/a

### Version requirement

- [X] I am using latest debug CI version of LSPosed and enable verbose log

### Logs

```
type: crash
osVersion: google/panther/panther:14/UQ1A.240105.004/2024011600:user/release-keys
package: com.android.shell:34
process: com.android.shell
processUptime: 0 + 0 ms

signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x0000cc67a25fa000

backtrace:
      #00 pc 000000000005abac  /apex/com.android.runtime/lib64/bionic/libc.so (__memcpy_aarch64_simd+44) (BuildId: 683448b69f8aa065d6038085038e8da0)
      #01 pc 000000000001d840  /memfd:jit-cache (deleted)
```
I'm not sure if this is useful, but...

[Shell log c16f1a4f6307.txt](https://github.com/mywalkb/LSPosed_mod/files/15163240/Shell.log.c16f1a4f6307.txt)

**Comment by mywalkb** [comment]
No debug log.
When you check "I am using latest debug CI version of LSPosed and enable verbose log" should be true.

**Comment by Archie-osu** [comment]
Having the same issue on the latest HyperOS weekly build with KernelSU. 

Not sure what logs you require, but here's the ones I gathered from /data/adb/lspd/logs
[kmsg.log](https://github.com/mywalkb/LSPosed_mod/files/15180374/kmsg.log)
[verbose_2024-05-01T20:58:54.684049.log](https://github.com/mywalkb/LSPosed_mod/files/15180376/verbose_2024-05-01T20.58.54.684049.log)

**Comment by mywalkb** [comment]
@Archie-osu try to install the apk with:

```
su
pm install /data/adb/modules/zygisk_lsposed/manager.apk
```
launch and let me to know if you have the same issue.

**Comment by Archie-osu** [comment]
Did this:
- Completely cleaned up LSPosed folders and uninstalled it from KernelSU
- Rebooted phone
- Did a fresh install of KernelSU, rebooted again
- Didn't touch LSPosed at all, instead ran your command and rebooted again (output of the command was simply "Success")

The LSPosed manager now appeared in the list of apps, and I was indeed able to get in and use it.
However, the notification icon still does not work (app crashed, and now tapping isn't doing anything at all) - launching the manager from the app list in this state seems to work just fine.

Here's the current logs:
[kmsg.log](https://github.com/mywalkb/LSPosed_mod/files/15180890/kmsg.log)
[verbose_2024-05-01T21:56:21.447906.log](https://github.com/mywalkb/LSPosed_mod/files/15180889/verbose_2024-05-01T21.56.21.447906.log)

**Comment by lefuglyduck** [comment]
To add to this, I've never had an issue opening the app from the launcher, only from the notifications (or the phone dialer), which means I can't "uninstall" the app.

**Comment by mywalkb** [comment]
>  However, the notification icon still does not work (app crashed, and now tapping isn't doing anything at all)

It's normal. Parasitic manager on the latest android has many issues and it's not easy to solve them
I'd like return to installed manager and use random package name for hide the manager.

> Edit: Tried using Pengeek, an app for customizing HyperOS that relies on Xposed, but none of the features seem to be working, which leaves me confused as to if LSPosed actually works.

This is another issue. I don't know Pengeek and I do not have HyperOS, it could be that your version of HyperOs is not compatible with the module.
Try a simpler module that works on an app instead of the Android framework.
So we can confirm if LSposed is working or no.
Looking at your log LSPosed was initialized successfully.

**Comment by mywalkb** [comment]
> To add to this, I've never had an issue opening the app from the launcher, only from the notifications (and the phone dialer), which means I can't "uninstall" the app.

From the launcher means: shortcut created or installed app?
Could you install debug version and post log from app?

**Comment by Archie-osu** [comment]
Sorry for not replying in a while, but I ended up solving the issue - it turns out that KernelSU hadn't allowed the manager (com.android.shell) root access - upon granting it, everything now works.

**Comment by lefuglyduck** [comment]
Weird, I don't even get a prompt for root and I can't add it manually with magisk.

**Comment by mywalkb** [comment]
> Sorry for not replying in a while, but I ended up solving the issue - it turns out that KernelSU hadn't allowed the manager (com.android.shell) root access - upon granting it, everything now works.

then it's no coincidence, in this [discussion](https://github.com/mywalkb/LSPosed_mod/discussions/79#discussioncomment-9174078) we talk about the same issue that was solved.
I have to do some tests, because I've always had com.android.shell with root access and I've never had the issue. I put it as a prerequisite to be able to use the parasitic manager.

> Weird, I don't even get a prompt for root and I can't add it manually with magisk.

parasitic manager don't require root. It talk with daemon lspd which has root privilege when needed.
If you run an `adb shell` and run `su`, you should receive the request from magisk to authorize the access.

**Comment by mywalkb** [comment]
I tested on avd android 14, com.android.shell without root access, parasitic manager works without issues.

**Comment by mywalkb** [comment]
@lefuglyduck have you solved?

**Comment by lefuglyduck** [comment]
Apologies, for the late response. I've been busy.

No, the issue still persists. I still can't open the manager via the notification. I can only open it via the launcher shortcut. I have not had the time to install the debug version.

**Comment by mywalkb** [comment]
Ok, when you are ready with logs, I will reopen the issue.

> E: where do I download the debug version? I can't find it.

[Here](https://github.com/mywalkb/LSPosed_mod/actions/workflows/core.yml?query=branch%3Amain)

**Comment by e-t-l** [comment]
@lefuglyduck do any of your lsposed modules actually work? I was under the impression that lsposed was incompatible with GrapheneOS...

**Comment by lefuglyduck** [comment]
Yes, they all work.
